runtime: nodejs14
env: flex

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 15
  cool_down_period_sec: 180

resources:
  cpu: 1
  memory_gb: 3.75
  disk_size_gb: 10

network: 
  forwarded_ports:
    - 5002/tcp

env_variables:
  PORT: 5002
  MONGODB_URL: "mongodb+srv://Alex:12345@cluster0.wwaslbh.mongodb.net/?retryWrites=true&w=majority"

entrypoint: node ./server.js